foundation/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.views.generic import TemplateView
from django.views.generic import RedirectView
from django.contrib.auth import views as admin_views
from django.views import defaults as default_views

from django.contrib import admin
from django.contrib.sitemaps.views import sitemap

from foundation.organisation.views import relatable_person

from haystack.views import SearchView
from cms.sitemaps import CMSSitemap

admin.autodiscover()

ARCHIVE_ROOT = 'http://webarchive.okfn.org/okfn.org/201404'

urlpatterns = [
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^robots.txt$', TemplateView.as_view(template_name="robots.txt",
                                              content_type="text/plain"),
        name="robots_file"),
    url('', include('sendemail.urls')),
]

# Allow testing of error pages in development
if settings.DEBUG:
    urlpatterns += [
        url(r'^400/$', default_views.bad_request),
        url(r'^403/$', default_views.permission_denied),
        url(r'^404/$', default_views.page_not_found),
        url(r'^500/$', default_views.server_error),
    ]

# Login/logout, password changes and resets
urlpatterns += [
    url(
        r'^login/$',
        admin_views.login,
        {'template_name': 'accounts/login.html'},
        name='login'),
    url(
        r'^logout/$',
        admin_views.logout,
        {'next_page': '/'},
        name='logout'
    ),
    url(
        r'^password/change/$',
        admin_views.password_change,
        name='password_change'
    ),
    url(
        r'^password/change/done/$',
        admin_views.password_change_done,
        name='password_change_done'
    ),
    url(
        r'^password/reset/$',
        admin_views.password_reset,
        name='password_reset'
    ),
    url(
        r'^password/reset/done/$',
        admin_views.password_reset_done,
        name='password_reset_done'
    ),
    url(
        r'^password/reset/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
        admin_views.password_reset_confirm,
        name='password_reset_confirm'
    ),
    url(
        r'^password/reset/complete/$',
        admin_views.password_reset_complete,
        name='password_reset_complete'
    ),
]

# Search patterns (do not use haystack.url
# since we're using an older version of haystack
# because of django-cms-search)
urlpatterns += [
    url(r'^search/', SearchView(), name='haystack_search'),
]

# CMS patterns
urlpatterns += [
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': {'cmspages': CMSSitemap}}),
    url(r'^sitemap/$',
        TemplateView.as_view(template_name='sitemap.html')),

    # Fallthrough prefix redirects. WARNING: these will override any pages
    # created in the CMS with these names.
    url(r'^blogs/(?P<remain>.+)$',
        RedirectView.as_view(url=ARCHIVE_ROOT + '/blogs/%(remain)s',
                             permanent=True)),
    url(r'^members/(?P<remain>.+)$',
        RedirectView.as_view(url=ARCHIVE_ROOT + '/members/%(remain)s',
                             permanent=True)),
    url(r'^wp-content/(?P<remain>.+)$',
        RedirectView.as_view(url=ARCHIVE_ROOT + '/wp-content/%(remain)s',
                             permanent=True)),
    url(r'^wp-includes/(?P<remain>.+)$',
        RedirectView.as_view(url=ARCHIVE_ROOT + '/wp-includes/%(remain)s',
                             permanent=True)),

    # we would like to properly do this from within the cms
    # but it does not work with `csrf_exempt`. See
    # https://github.com/divio/django-cms/issues/4599
    url(r'^api$', relatable_person, name='relatable-person'),

    # Fallthrough for CMS managed pages
    url(r'^', include('cms.urls'))
]

sendemail/urls.py
from django.conf.urls import url
# from django.contrib import admin

from . import views

urlpatterns = [
    url('contact/', views.contactview, name='contact'),
]

foundation/organisation/models.py
from hashlib import md5

from cms.models.pluginmodel import CMSPlugin
from cms.extensions import PageExtension
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.text import slugify
from django_countries.fields import CountryField


class Person(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    name = models.CharField(max_length=100)
    username_on_slack = models.CharField(max_length=100, blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    email = models.EmailField(blank=True)
    photo = models.ImageField(upload_to='organisation/people/photos',
                              blank=True)
    twitter = models.CharField(max_length=18, blank=True)
    url = models.URLField(blank=True)

    NOWDOING_DEFAULT_ORDER = (
        'working', 'location', 'reading', 'listening', 'watching', 'eating'
    )

    def __str__(self):
        return self.name

    @property
    def gravatar_url(self):
        """ Returns the gravatar url for this user (constructed from email)"""
        base = "https://gravatar.com/avatar/{hash}?s=132"
        md5_hash = md5(self.email.strip().lower().encode("utf-8")).hexdigest()
        return base.format(hash=md5_hash)

    @property
    def nowdoing_with_latest(self):
        """ All NowDoing attributes of the user with the most recently
            updated one marked with `is_newest_update`"""
        nowdoings = self.nowdoing_set.all().extra(order_by=['-updated_at'])
        if nowdoings:
            nowdoings[0].is_newest_update = True
        return nowdoings

    @property
    def nowdoing_by_custom_order(self, custom_order=None):
        custom_order = custom_order or self.NOWDOING_DEFAULT_ORDER
        nowdoings = self.nowdoing_with_latest
        ordered_nowdoings = list()
        for doing_type in custom_order:
            if nowdoings.filter(doing_type=doing_type):
                ordered_nowdoings.append(
                    nowdoings.filter(doing_type=doing_type).first())
        return ordered_nowdoings

    @property
    def has_anything_to_show(self):
        """ Is there anything that we can show for this person in the
            template (other then email which is checked separately)"""
        return (self.url
                or self.twitter
                or self.nowdoing_set.count())

    class Meta:
        ordering = ["name"]
        verbose_name_plural = "people"


class NowDoing(models.Model):
    ACTIVITIES = (
        ('reading', 'reading'),
        ('listening', 'listening'),
        ('working', 'working'),
        ('location', 'location'),
        ('watching', 'watching'),
        ('eating', 'eating'),
    )
    person = models.ForeignKey(Person)
    doing_type = models.CharField(
        max_length=10,
        choices=ACTIVITIES)
    link = models.URLField(blank=True, null=True)
    text = models.TextField(blank=True, null=True)
    updated_at = models.DateTimeField(auto_now=True)

    @property
    def icon_name(self):
        """ The name of the corresponding css icon class """
        matching = {'watching': 'playing'}
        return matching.get(self.doing_type, self.doing_type)

    @property
    def display_name(self):
        """ The human readable string to be displayed in templates """
        matching = {
            'reading': 'Reading',
            'listening': 'Listening to',
            'working': 'Working on',
            'location': 'Location',
            'watching': 'Watching',
            'eating': 'Eating'
        }
        return matching.get(self.doing_type, self.doing_type)

    def __repr__(self):
        return '<NowDoing: {}, {}>'.format(self.person.name,
                                           self.doing_type)


class Unit(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    name = models.CharField(max_length=100)
    members = models.ManyToManyField('Person', through='UnitMembership')
    order = models.IntegerField(
        blank=True, null=True,
        help_text="Higher numbers mean higher up in the list")

    def __str__(self):
        return self.name

    class Meta:
        ordering = ["-order", "name"]


class UnitMembership(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    title = models.CharField(max_length=100)
    person = models.ForeignKey('Person')
    unit = models.ForeignKey('Unit')
    order = models.IntegerField(
        blank=True, null=True,
        help_text="Higher numbers mean higher up in the list")

    def __str__(self):
        return self.person.name + ' - ' + self.title

    class Meta:
        ordering = ["-order", "person__name"]


class Board(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100, unique=True)
    description = models.TextField()

    members = models.ManyToManyField('Person', through='BoardMembership')

    def __str__(self):
        return self.name


class BoardMembership(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    title = models.CharField(max_length=100)
    person = models.ForeignKey('Person')
    board = models.ForeignKey('Board')
    order = models.IntegerField(
        blank=True, null=True,
        help_text="Higher numbers mean higher up in the list")

    def __str__(self):
        return self.person.name + ' - ' + self.title

    class Meta:
        ordering = ["-order", "person__name"]


class Project(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    old_project = models.BooleanField(
        default=False,
        help_text='Is this an old/archived project?')

    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100, unique=True)
    teaser = models.CharField(
        max_length=400,
        help_text="A single line description for list views")
    description = models.TextField()
    picture = models.ImageField(
        upload_to='projects/pictures',
        blank=True,
        help_text="A simple logo or picture to represent this project")

    twitter = models.CharField(max_length=18, blank=True)
    homepage_url = models.URLField(blank=True)
    sourcecode_url = models.URLField(blank=True)
    forum_url = models.URLField(blank=True)

    themes = models.ManyToManyField('Theme', blank=True)
    types = models.ManyToManyField('ProjectType', blank=True)

    def get_absolute_url(self):
        return reverse('project', kwargs={'slug': self.slug})

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('name',)


class ProjectType(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100, unique=True)

    def __str__(self):
        return self.name


class Theme(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100, unique=True)
    blurb = models.TextField(help_text='Blurb for theme page')
    description = models.TextField()
    picture = models.ImageField(
        upload_to='themes/pictures',
        blank=True,
        help_text="A simple logo or picture to represent this theme")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('theme', kwargs={'slug': self.slug})


class WorkingGroupManager(models.Manager):
    def active(self):
        return self.get_queryset().filter(incubation=False)

    def incubators(self):
        return self.get_queryset().filter(incubation=True)


class WorkingGroup(models.Model):
    objects = WorkingGroupManager()

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100, unique=True)

    description = models.TextField()
    homepage_url = models.URLField(blank=True)
    logo = models.ImageField(upload_to='organisation/working-groups/logos',
                             blank=True)

    incubation = models.BooleanField(default=True,
                                     help_text='Is this group in incubation?')

    themes = models.ManyToManyField('Theme', blank=True,
                                    related_name='workinggroups')

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('name',)


class NetworkGroupManager(models.Manager):
    def countries(self):
        return self.get_queryset().filter(region_slug='')

    def regions(self, country):
        return self.get_queryset().exclude(region_slug='') \
            .filter(country_slug=country)


class NetworkGroup(models.Model):
    objects = NetworkGroupManager()

    GROUP_TYPES = ((0, 'Local group'),
                   (1, 'Chapter'),
                   (2, 'Established group'),
                   (3, 'Incubating group'),
                   (4, 'Hibernated group'),
                   (5, 'Affiliate')
                   )

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    name = models.CharField(max_length=100)

    group_type = models.IntegerField(default=0, choices=GROUP_TYPES)
    description = models.TextField(blank=True, null=True)

    country = CountryField()
    country_slug = models.SlugField()
    region = models.CharField(max_length=100, blank=True)

foundation/organisation/templates/organisation/board_details.html
{% extends "cms_apphook.html" %}
{% load cms_tags %}

{% block title %}{{ object.name }}{% endblock %}

{% block pagebanner-inner %}
<h2>{{ object.name }}</h2>
<p>{{ object.description }}</p>
{% endblock %}

{% block custom_sidebar %}
  <h3>Members</h3>
  <ul>{% for membership in object.boardmembership_set.all %}
    <li><a href="#{{ membership.person.name|slugify }}">{{ membership.person.name }}</a></li>
    {% endfor %}</ul>
    {% static_placeholder object.name|truncatechars:10|add:" (sidebar)" %}
{% endblock %}

{% block main %}
      {% with skip_email=True %}
      {% for member in object.boardmembership_set.all %}
        {% include "organisation/member.html" %}
      {% endfor %}
      {% endwith %}
{% endblock %}

foundation/organisation/templates/organisation/member.html
{% load markdown_deux_tags %}
{% load staticfiles %}

{% with person=member.person %}
    <div class="row">
        <div class="profile col-md-12" id="{{ person.name|slugify }}">
            <span class="image" style="background-image: url(
            {% if person.photo %}{{ person.photo.url }}{% else %}{{ person.gravatar_url }}{% endif %});"><img
                    src="{% static 'img/blank.png' %}" alt=""/></span>
            <h3 class="name">{{ person.name }}</h3>
            {% if member.title %}
                <p class="job-title">{{ member.title }}</p>
            {% endif %}
            {{ person.description|markdown }}
            {% with a=person.all_now_doing_by_type %}
                <p>{% if a.watching %}{{ a.watching }}{% endif %}</p>
            {% endwith %}
            {% if person.has_anything_to_show or person.email and not skip_email %}
                <div class="meta">
                    <div class="tab-content">
                        {% if person.email and not skip_email %}
                            <div role="tabpanel"
                                 class="tab-pane active"
                                 id="{{ person.name|slugify }}-email">
                                <h4>Email:</h4>
                                {{ person.email }}
                            </div>
                        {% endif %}

                        {% if person.twitter %}
                            <div role="tabpanel" class="tab-pane{% if skip_email %} active{% endif %}" id="{{ person.name|slugify }}-twitter">
                                <h4>Twitter:</h4>
                                <a href="https://twitter.com/{{ person.twitter }}"> {{ person.twitter }} </a>
                            </div>
                        {% endif %}

                        {# TODO: Add location #}
                    </div>

                    <ul class="nav nav-tabs" role="tablist">
                        {% if person.email and not skip_email %}
                            <li role="presentation">
                                <a class="nav-link active" href="#{{ person.name|slugify }}-email"
                                   aria-controls="{{ person.name|slugify }}-email"
                                   role="tab"
                                   data-toggle="tab">
                                    <span class="icon-mail" aria-hidden="true"></span>
                                    <span class="sr-only">Email</span>
                                </a>
                            </li>
                        {% endif %}

                        {% if person.twitter %}
                            <li role="presentation">
                              <a class="nav-link{% if skip_email %} active{% endif %}" href="#{{ person.name|slugify }}-twitter"
                                                       aria-controls="{{ person.name|slugify }}-twitter" role="tab"
                                                       data-toggle="tab"><span class="icon-twitter"
                                                                               aria-hidden="true"></span>
                                <span class="sr-only">Twitter</span></a></li>
                        {% endif %}

                        {# TODO: Add location - use .icon-map-pin #}
                    </ul>
                </div>
            {% endif %}
        </div>
    </div>
{% endwith %}

foundation/organisation/templates/organisation/networkgroup_detail.html
{% extends "cms_apphook.html" %}
{% load i18n %}
{% load markdown_deux_tags %}
{% load cms_tags %}
{% block title %}{{ object.name }}{% endblock %}

{% block pagebanner %}
  <div class="banner">
    <div class="container">
      <div class="banner_text">
        <h2>{{ object.name }}</h2>
        {{ object.description|markdown }}
      </div>
      <div class="banner_image">
        {% placeholder "banner image" inherit %}
      </div>
    </div>
  </div>
{% endblock %}

{% block custom_sidebar %}
    <h3>Connect</h3>
    <ul>
        <li>
                <span class="icon-globe" aria-hidden="true"></span>
            {% if object.region %}{{ object.region }}, {% endif %}{{ object.get_country_display }}
        </li>
        {% if object.region %}
            <li>
                <span class="icon-arrow-up" aria-hidden="true"></span>
                <a href="{% url "network-country" country=object.country_slug %}"
                   alt="Group for {{ object.get_country_display }}">
                    Our country group
                </a>
            </li>
        {% endif %}
        {% if object.homepage_url %}
            <li>
                <span class="icon-link" aria-hidden="true"></span>
                <a href="{{ object.homepage_url }}">{{ object.homepage_url }}</a>
            </li>
        {% endif %}
        {% if object.mailinglist_url %}
            <li>
                <span class="icon-mail" aria-hidden="true"></span>
                <a href="{{ object.mailinglist_url }}">Mailing list</a>
            </li>
        {% endif %}
        {% if object.twitter %}
            <li>
                <span class="icon-twitter2" aria-hidden="true"></span>
                <a href="http://twitter.com/{{ object.twitter }}">
                    @{{ object.twitter }}
                </a>
            </li>
        {% endif %}
        {% if object.facebook_url %}
            <li>
                <span class="icon-facebook-square" aria-hidden="true"></span>
                <a href="{{ object.facebook_url }}">
                    Facebook page
                </a>
            </li>
        {% endif %}
        {% if object.forum_group_url %}
            <li>
                <span class="icon-comments"></span>
                <a href="{{ object.forum_group_url }}">
                    Forum Group
                </a>
            </li>
        {% endif %}
    </ul>
    {% if regional_groups %}
        <h3>Our Regional Groups</h3>
        {% for group in regional_groups %}
            <ul>
                <li><a href="{{ group.get_absolute_url }}">{{ group.name }}</a></li>
            </ul>{% endfor %}
    {% endif %}
    {% if object.working_groups.all %}
        <h3>Interest Areas</h3>
        <p>
            Members of this {{ object.get_group_type_display|lower }}
            are active in the following Open Knowledge working group:
        </p>
        {% for group in object.working_groups.all %}
            <ul>
                <li><a href="{{ group.homepage }}">{{ group.name }}</a></li>
            </ul>{% endfor %}
    {% endif %}
{% endblock %}

{% block main %}
    <h3>Core team</h3>
    {% for member in group_members %}
        {% include "organisation/member.html" %}
    {% endfor %}

    {% if object.extra_information %}
        <h3>More information</h3>
        {{ object.extra_information|markdown }}
    {% endif %}
{% endblock %}

foundation/organisation/templates/organisation/project.html
{% load markdown_deux_tags %}

<h3>{{ project.name }}</h3>
{{ project.description|markdown }}

<ul class='project-icon-list icon-list'>
  {% if project.twitter %}
  <li>
    <a href='https://twitter.com/{{ project.twitter }}'
      title='@{{ project.twitter }} on Twitter'>
      <i class='fa fa-twitter fa-lg fa-fw twitter'></i>
      @{{ project.twitter }} on Twitter
    </a>
  </li>
  {% endif %}
  {% if project.homepage_url %}
  <li>
    <a href='{{ project.homepage_url }}'
      title='Project homepage'>
      <i class='fa fa-home fa-lg fa-fw'></i> Homepage
    </a>
  </li>
  {% endif %}
  {% if project.sourcecode_url %}
  <li>
    <a href='{{ project.sourcecode_url }}'
      title='Project source code'>
      <i class='fa fa-code fa-lg fa-fw'></i> Source code
    </a>
  </li>
  {% endif %}
  {% if project.mailinglist_url %}
  <li>
    <a href='{{ project.mailinglist_url }}'
      title='Project mailing list'>
      <i class='fa fa-envelope fa-lg fa-fw'></i> Mailing list
    </a>
  </li>
  {% endif %}
</ul>

foundation/organisation/templates/organisation/project_detail.html
{% extends "cms_apphook.html" %}
{% load i18n %}
{% load thumbnail %}

{% block title %}{{ object.name }}{% endblock %}

{% block main %}
<div class="row">

{% if object.picture %}
  <div class="main col-md-9 col-md-push-3">
    {% with project=object %}
    {% include "organisation/project.html" %}
    {% endwith %}
  </div>
  <div class="sidebar col-md-3 col-md-pull-9">
    <img
      class="img-responsive"
      src="{% thumbnail project.picture 263x263 %}"
      alt="Logo/banner for {{ object.name }}"
    >
  </div>
{% else %}
  <div class="main col-md-12">
    {% with project=object %}
    {% include "organisation/project.html" %}
    {% endwith %}
  </div>
{% endif %}
</div>
{% endblock %}

foundation/organisation/templates/organisation/project_featured.html
{% load markdown_deux_tags %}
{% load thumbnail %}
<div class="featured-project col-md-4 col-sm-6">
    <h3 class="sr-only">{{ project.name }}</h3>
    <img
      class="img-responsive"
      src="{% thumbnail project.picture 375x375 %}"
      alt="Banner for {{ project.name }}"
    >
  <p class="featured-project-teaser">{{ project.teaser }}</p>
</div>

foundation/organisation/templates/organisation/project_list.html
{% extends "cms_apphook.html" %}
{% load i18n %}
{% load cms_tags %}
{% load markdown_deux_tags %}
{% load thumbnail %}

{% block blurb %}{% static_placeholder "projects blurb" %}{% endblock %}

{% block main %}
<div class="row">
  {% static_placeholder "projects intro" %}
</div>
{% for project in object_list %}
<div class="row">
  <div class="profile">
    <img src="{% thumbnail project.picture 132x132 %}" alt="" />
    <h3 class="name">{{ project.name }}</h3>

    {{ project.teaser|markdown }}

    {% if project.twitter or project.sourcecode_url or project.homepage_url or project.forum_url %}
    <div class="meta">
      <div class="tab-content">

        {% if project.homepage_url %}
        <div role="tabpanel" class="tab-pane" id="{{project.name|slugify}}-home">
          <h4>Homepage:</h4>
          <a href="{{ project.homepage_url }}"> {{ project.homepage_url }}</a>
        </div>
        {% endif %}

        {% if project.sourcecode_url%}
        <div role="tabpanel" class="tab-pane" id="{{project.name|slugify}}-sourcecode_url">
           <h4>Sourcecode:</h4>
           <a href="{{ project.sourcecode_url }}"> {{ project.sourcecode_url }}</a>
        </div>
        {% endif %}

        {% if project.forum_url %}
        <div role="tabpanel" class="tab-pane" id="{{project.name|slugify}}-forum_url">
           <h4>Forum:</h4>
           <a href="{{ project.forum_url }}">{{ project.forum_url }}</a>
        </div>
        {% endif %}

        {% if project.twitter %}
        <div role="tabpanel" class="tab-pane" id="{{project.name|slugify}}-twitter">
          <h4>Twitter:</h4>
          <a href="https://twitter.com/{{project.twitter}}"> {{ project.twitter }} </a>
        </div>
        {% endif %}


      </div>

      <ul class="nav nav-tabs" role="tablist">

        {% if project.homepage_url %}
        <li role="presentation"><a href="#{{project.name|slugify}}-home" aria-controls="{{project.name|slugify}}-home" role="tab" data-toggle="tab"><span class="icon-home-circle" aria-hidden="true"></span>
        <span class="sr-only">Homepage</span></a></li>
        {% endif %}

        {% if project.sourcecode_url %}
        <li role="presentation">
          <a href="#{{project.name|slugify}}-sourcecode_url"
             aria-controls="{{project.name|slugify}}-sourcecode_url"
             role="tab"
             data-toggle="tab">
            <span class="icon-code-circle" aria-hidden="true"></span>
            <span class="sr-only">Email</span>
          </a>
        </li>
        {% endif %}

        {% if project.forum_url %}
        <li role="presentation"><a href="#{{project.name|slugify}}-forum_url" aria-controls="{{project.name|slugify}}-forum_url" role="tab" data-toggle="tab"><span class="icon-forum-circle" aria-hidden="true"></span>
        <span class="sr-only">Forum</span></a></li>
        {% endif %}

        {% if project.twitter %}
        <li role="presentation"><a href="#{{project.name|slugify}}-twitter" aria-controls="{{project.name|slugify}}-twitter" role="tab" data-toggle="tab"><span class="icon-twitter-circle" aria-hidden="true"></span>
          <span class="sr-only">Twitter</span></a></li>
        {% endif %}
      </ul>
    </div>
    {% endif %}
  </div>
</div>
{% endfor %}



{% with timeless=True %}
{% include "includes/pager.html" %}
{% endwith %}
{% endblock %}

foundation/organisation/templates/organisation/theme_detail.html
{% extends "cms_apphook.html" %}
{% load i18n %}
{% load thumbnail %}
{% load markdown_deux_tags %}

{% block title %}{{ object.name }}{% endblock %}

{% block pagebanner-inner %}
<h2>{{ object.name }}</h2>
<p>{{ object.blurb|markdown }}</p>
{% endblock %}

{% block custom_sidebar %}
    <h3>Other themes</h3>
    <ul>
      {% for theme in themes %}
        <li><a href="{{ theme.get_absolute_url }}">{{ theme.name }}</a></li>
      {% endfor %}
    </ul>
{% endblock %}

{% block main %}
    {{ object.description|markdown }}
    <div class="row">
      {% if object.workinggroups.all %}
      <div class="col-md-6 col-sm-12">
        <h3>Working Groups</h3>
        {% for group in object.workinggroups.all %}
        <h4>
          <a href="{{ group.homepage_url }}" target="_blank">
            {{ group.name }}
          </a>
        </h4>
        <div class="row">
          <div class="col-md-3 col-sm-12">
            <div class="center-block">
              <a href="{{ group.homepage_url }}">
                <img
                  class="img-responsive"
                  src="{% thumbnail group.logo 64x64 %}"
                  alt="Logo for {{ group.name }}"
                >
              </a>
            </div>
          </div>
          <div class="col-md-9 col-sm-12">
            {{ group.description }}
          </div>
        </div>
        {% endfor %}
      </div>
      {% endif %}
      {% if object.project_set.all %}
      <div class="col-md-6 col-sm-12">
        <h3>Projects</h3>
        {% for project in object.project_set.all %}
        <h4>{{ project.name }}</h4>
        <div class="row">
          <div class="col-md-3 col-sm-12">
            <div class="center-block">
              <img
                class="img-responsive"
                src="{% thumbnail project.picture 64x64 %}"
                alt="Logo/banner for {{ project.name }}"
              >
            </div>
          </div>
          <div class="col-md-9 col-sm-12">
            {{ project.teaser }}
          </div>
        </div>
        {% endfor %}
      </div>
      {% endif %}
    </div>
  </article>
</div>
{% endblock %}

foundation/organisation/templates/organisation/unit_list.html
{% extends "cms_apphook.html" %}

{% load i18n %}
{% load cms_tags %}
{% load markdown_deux_tags %}

{% block blurb %}{% static_placeholder "units blurb" %}{% endblock %}

{% block main %}
  {% for unit in unit_list %}
    <h2 id='{{ unit.name | slugify }}'>{{ unit.name }}</h2>
    {% for member in unit.unitmembership_set.all %}
      {% include "organisation/member.html" %}
    {% endfor %}
  {% endfor %}
{% endblock %}